name: CI
on:
  push:
    branches-ignore:
      - master
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run tests
        run: pnpm -r test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run lint
        run: pnpm -r lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run build
        run: pnpm -r build
